# 1. numpy基础

In [1]:
import numpy as np

In [4]:
ls = [255]
array = np.array(ls,dtype=np.uint8)
new = 1.0+array
print(new)
print(new.dtype)

[256.]
float64


## 1.1 创建矩阵

In [5]:
# 直接把python的组合数据类型变成numpy的ndarray类型
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
array = np.array(ls)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# numpy数组的属性
print( type(array) )
print( array.ndim )
print( array.size )
print( array.shape )
print( array.dtype )
print( array.itemsize )

<class 'numpy.ndarray'>
2
9
(3, 3)
int32
4


In [4]:
# 创建全零矩阵
zeros = np.zeros(shape=(3, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
# 创建全1矩阵
ones = np.ones(shape=(1,3,5))
print(ones)
ones = np.squeeze(ones)
print(ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# 创建顺序数组
aranged = np.arange(90)
print(aranged)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [7]:
# 创建单位矩阵
print( np.eye(5) )

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# 创建等差数列
print( np.linspace(0,5,5) )

[0.   1.25 2.5  3.75 5.  ]


In [9]:
# 创建等比数列
print( np.logspace(0,5,5) )

[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]


## 1.2 改变数组形状

In [10]:
aranged = np.arange(90)
print(aranged)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [11]:
new = np.arange(90).reshape(3,3,10)
print(new)
print(aranged)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]]

 [[30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [12]:
aranged.resize(3,3,10)
print(aranged)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]]

 [[30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]]]


In [13]:
print(aranged.flatten())
print(aranged.flatten().shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
(90,)


## 1.3 数组间的运算

In [14]:
a = np.array([0,1,2])
b = np.array([[0,1,2],
              [1,2,3],
              [2,3,4]])
print(a+b)

[[0 2 4]
 [1 3 5]
 [2 4 6]]


In [15]:
print( b+b )

[[0 2 4]
 [2 4 6]
 [4 6 8]]


In [16]:
print( b**2 )

[[ 0  1  4]
 [ 1  4  9]
 [ 4  9 16]]


In [17]:
# 矩阵乘法
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A*B)   # 矩阵中对应元素相乘
print(np.matmul(A,B))    # 真正的矩阵乘法
print(np.dot(A,B))    # 真正的矩阵乘法

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [18]:
# 计算array中所有元素的和
np.sum(np.arange(0,5))

10

In [19]:
# 计算array中所有元素的乘积
np.prod(np.arange(1,5))

24

In [20]:
# 计算array相邻元素的差
np.diff(np.arange(1,5))

array([1, 1, 1])

In [21]:
# 计算各个元素的平方根
np.sqrt(np.arange(1,5))

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [22]:
# 计算各个元素的指数值
np.exp(np.arange(1,5))

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [23]:
# 计算各个元素的绝对值
np.abs(np.arange(1,5))

array([1, 2, 3, 4])

## 1.4 制造随机数

In [24]:
print( np.random.rand(5,5) )

[[0.77871238 0.21100229 0.69052051 0.91309704 0.7655684 ]
 [0.82432556 0.61605087 0.22958667 0.8654768  0.85921136]
 [0.07152624 0.4912109  0.18524835 0.10302316 0.18218113]
 [0.35418698 0.26239631 0.51294209 0.11071256 0.63740707]
 [0.41311158 0.89756948 0.89511186 0.86196821 0.55249305]]


In [25]:
print( np.random.uniform(0, 1, size=(5,5)) )

[[0.92440068 0.18955247 0.55530979 0.60131073 0.89646756]
 [0.6671816  0.09658523 0.23113908 0.69416441 0.36321157]
 [0.58702998 0.64824768 0.96230375 0.41414135 0.68140457]
 [0.37174061 0.75790262 0.54629799 0.23796997 0.87384788]
 [0.10121522 0.08146323 0.52528526 0.25284946 0.47185468]]


In [26]:
print( np.random.randint(0, 10, size=(5,5)) )

[[3 8 5 6 5]
 [2 8 3 5 9]
 [7 4 9 5 6]
 [1 1 8 0 7]
 [5 6 9 5 9]]


In [27]:
print( np.random.randn(5,5) )

[[-1.45558473 -0.85622501 -0.55784763 -0.2708915  -0.88308935]
 [ 3.37007365 -0.95722823  2.90623484 -1.47689277 -0.96219421]
 [ 0.69550896 -0.17023134 -0.82167888  0.37536106 -0.52401171]
 [-0.28315369  2.1759043  -1.75123672 -1.49618023  0.07097634]
 [-1.7080525   0.97569435 -1.78029102 -0.28271159 -0.05889504]]


In [28]:
print( np.random.normal(0, 1, size=(5,5)) )

[[ 0.00280084  0.83778215  0.52947246  0.40842442  0.73983035]
 [-2.44313214  0.31378212  0.27705944  0.19353715  1.8663426 ]
 [-1.65996287  1.60750982  1.32275945  0.20854577  1.85458187]
 [-0.16649902  0.36404739 -1.33870956 -0.42681328  0.31308893]
 [-1.37391606 -0.75459005 -1.63332974 -1.57849983 -0.5121208 ]]


## 1.5 numpy的ndarray转换成python的列表类型

In [29]:
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
array = np.array(ls)
print(array.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [30]:
print(array.flatten().tolist())

[1, 2, 3, 4, 5, 6, 7, 8, 9]


## 1.6 ndarray和list的区别？？

In [31]:
# ndarray
array1 = np.array([[1,2,3],
                   [1,2,3],
                   [1,2,3]])

array2 = np.array([[3,2,1],
                   [3,2,1],
                   [3,2,1]])

array_sum = array1 + array2
print('array1 + array2 = \n', array_sum)

array_diff = array1 - array2
print('array1 - array2 = \n', array_diff)

array_diff_squared = array_diff ** 2
print('array_diff_squared ** 2 = \n', array_diff_squared)

array_diff_squared_sqrted = np.sqrt(array_diff_squared)
print('sqrt(array_diff_squared) = \n', array_diff_squared_sqrted)

array_diff_squared_sqrted_sumed = np.sum(array_diff_squared_sqrted)
print('sum(array_diff_squared_sqrted) = \n', array_diff_squared_sqrted_sumed)

array1 + array2 = 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
array1 - array2 = 
 [[-2  0  2]
 [-2  0  2]
 [-2  0  2]]
array_diff_squared ** 2 = 
 [[4 0 4]
 [4 0 4]
 [4 0 4]]
sqrt(array_diff_squared) = 
 [[2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]]
sum(array_diff_squared_sqrted) = 
 12.0


In [32]:
# list
ls1 = [[1,2,3],
       [1,2,3],
       [1,2,3]]

ls2 = [[3,2,1],
       [3,2,1],
       [3,2,1]]

print(ls1 + ls2)

print(ls1 ** 2)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [3, 2, 1], [3, 2, 1], [3, 2, 1]]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

以上内容可基本支撑该课程实验

更多教程详见网页：https://www.numpy.org.cn/user/quickstart.html